### ISSUE TITLE
[1.16.5] [Issue] Breaker Module does not pull broken item in buffer

### ISSUE THREAD

**Issue by accessdenied0** [desht/ModularRouters#149] opened 2021-11-10 14:41 UTC
### Minecraft Version
1.16.5
### Forge Version
36.2.9
### Mod Version
7.5.1-69
### Describe your problem, including steps to reproduce it

In the description of the breaker Module it states that it pulls any broken block in the buffer. The issue is that it only breaks the block but not pull it in the buffer. I would need to have install a collector upgrade as well to claim the block, but that appears in some situations a bit unsafe (e.g. with Lava above it).

I am quite unsure which mod it might causes... and the logs seem fine, because no errors. I checked FTB-Chunks and FTB-Teams and all seem to be fine/enabled for fake players.

### Any other comments?

I can try to provide a mod-list but I do not expect others to test every single mod for themselves.
I provide a Forge log here: [latest.log](https://github.com/desht/ModularRouters/files/7513509/latest.log)
I was mostly hoping someone has a clue or idea what it might cause it, or which kind of mods I should look out for. I already pinned pointed a "hopper modification" for a different issue with pulling blocks out of the Modular Router (Better Hoppers).

I apologies for the inconvenience.

**Comment by desht** [comment] 2021-11-11 12:27
Not seeing this behaviour at all.  Breaker module always pulls the block's drop into the buffer when I test.

Please provide a specific example of a block which doesn't get pulled into the buffer when broken.

**Comment by accessdenied0** [comment] 2021-11-11 20:01
I can show the setup:
![IssueBreaker2](https://user-images.githubusercontent.com/8020013/141359303-f8f96b49-3c05-4578-b1d0-a78bad58f170.gif)

In this example I use the CobblegenRandomizer. I had it working with it already, but I tried it without anyway. No diffe
rence.

I am quite puzzled which mod it might cause... I disabled some but so far no luck...

[ I attached the Instance. ](https://github.com/desht/ModularRouters/files/7523472/Almost.Vanilla-0.1Alpha.zip) (Curseforge)

**Comment by desht** [comment] 2021-11-12 08:41
Hmm, I have to admit I don't know what could be causing that.  Something must be messing with the block's loot tables, possibly when broken by a fake player.  What exactly is your breaker module (i.e. what pick was it crafted with)?  Can I see a screenshot of the tooltip when you mouse over it?

**Comment by desht** [comment] 2021-11-12 09:43
So I did a bit of debugging with the pack, and I can reproduce the problem.  What's happening is that some other mod in the pack is cancelling the block break event that Modular Routers posts (I do this to honour chunk protection), but breaking the block anyway.  So it isn't even Modular Routers that's breaking the block.

Whichever mod is doing this is at fault because causing a block to be broken after cancelling a break event is broken behaviour.

Unfortunately it's not easy to work out which mod is at fault.  The best way is a "binary chop" - remove half the mods and see if the bug remains.  If it does, remove half the remaining mods; if the bug disappears, restore half the removed mods.  Repeat until narrowed down to the culprit.  This is made more difficult by mod dependencies.

**Comment by desht** [comment] 2021-11-12 10:25
The mod in question is Crimson Harvester - on removing that, my routers started picking up breaks again as expected.  Try removing that from your pack.

**Comment by accessdenied0** [comment] 2021-11-12 10:47
Diamond Pick. A creative Spawned does the same..

... funny I was about to write that it was exactly that mod... XD I spend some time on that and had finally a 50/50 with Crimson Silk Touch. (A mod which enables Silk-Touching Chest to remain contents)

But it is good it got figured out. I thank you alot for your patience with my issue^^

**Comment by desht** [comment] 2022-01-17 13:29
Closing this, there isn't anything else I can do here.

**Closed as completed by desht** 2022-01-17 13:29 UTC
Labels: other mod issue
