### ISSUE TITLE
Fluid Module wastes fluid when fluid is already present in world.

### ISSUE THREAD

**Issue by Flanks255** [desht/ModularRouters#49] opened 2018-09-12 13:12 UTC
MC 1.12.2
Forge: Anything recent, but double checked with 14.23.4.2760
Modular routers: 3.2.0

Fluid module wastes fluid trying to place in world when it exists already.

Steps to reproduce:
Set up a router, with a fluid module set to transfer out of router, to say, the left.
Put a tank inside, fill it with water
Let it place 1 bucket of water.
Watch as the tank drains by 1 bucket every time the router processes.

I can upload a video demonstrating it if needed.

**Comment by desht** [comment] 2018-09-13 08:01
This is technically not a bug, but just the way Minecraft behaves with fluids.

If you take a bucket of any fluid, and right-click the bucket on a pool of that fluid, the bucket empties and you don't get your fluid back.  The Fluid Module is doing exactly the same thing.

Having said that, I appreciate it's not ideal given that the router can't easily sense what's there, unlike a player manually emptying a bucket.  What I can do is a add a checkbox to the fluid module to allow or prevent the module emptying fluid when the destination block isn't completely empty.  Default would be prevent emptying.

**Comment by desht** [comment] 2018-10-02 07:01
Fixed in 3.2.1 release.

**Closed as completed by desht** 2018-10-02 07:01 UTC
Labels: fixed in dev
