### ISSUE TITLE
Unable to remove old entries in filters

### ISSUE THREAD

**Issue by CorgiZero** [desht/ModularRouters#93] opened 2020-10-20 05:43 UTC
### Mod Version 7.1.0-35

When using the Inspection, Mod, or Regex filter, I can't remove old filter entries. The X that removes them is always greyed out, regardless of if there's something there or not. It makes it where any filter (other than Bulk) is essentially bricked if you input the wrong thing, as you can't go back and change it. Please correct me if i've missed something.

**Comment by desht** [comment] 2020-10-20 08:19
Sorry, not seeing this behaviour at all (tested both single player and dedicated server).  Filters behave exactly as expected, with X buttons being available when there's an entry to delete.

You'll need to provide a more detailed description of how you're configuring the filters (screenshots or video ideal)

**Comment by desht** [comment] 2020-10-20 08:21
I do see a sync issue when configuring a filter that's installed in a module - adding or removing something doesn't seem to do anything, but closing & reopening the filter GUI does show the changes.  So changes are happening serverside, just not being sync'd to client.  But the X buttons are not greyed out...

**Comment by CorgiZero** [comment] 2020-10-20 15:18
That's strange, if it helps at all I'm playing on the modpack TNP Limitless 3, on the official server. I'll post screenshots as soon as I can, but I can confirm it's an issue for others on the server too. Are there any mods that are specifically incompatible with this one?

**Comment by desht** [comment] 2020-10-20 15:29
I'm not aware of any specific incompatibilities, no.

**Comment by CorgiZero** [comment] 2020-10-22 00:37
Sorry about the delay, but here's some screenshots. These are in survival on the server for TNP Limitless 3, but it also occurs in singleplayer on this pack.

I've been trying to use this to sort enchanted items out of a mob farm, for context.
![image](https://user-images.githubusercontent.com/48398721/96804328-54b3dc00-13d4-11eb-9cca-d4892e560215.png)

Can't remove the [Enchantment < 0] entry, which i know i've done incorrectly for what i need. But i can't remove it on this or any other filter.
![image](https://user-images.githubusercontent.com/48398721/96804370-6e552380-13d4-11eb-89d3-af745013d96f.png)

Another, different filter that i clogged up trying to figure out why i couldn't remove entries.
![image](https://user-images.githubusercontent.com/48398721/96804481-bf651780-13d4-11eb-8f96-474a4cadf394.png)

I hope i'm not simply missing something, but as far as i can tell there's no way to remove them. Thank you for responding.

**Comment by desht** [comment] 2020-10-22 05:18
I can only guess that some other mod is interfering here. I have never seen this behaviour, and I have been unable to reproduce it on my test server or in my dev environment.

Could you screenshot the tooltip with Ctrl held down so I can see the full nbt tag?

Update: I installed TNP and yes I can reproduce the problem there.  So I'd guess some mod in that pack is interfering somehow.  I'll do some debugging and see if I can work out what.

**Comment by desht** [comment] 2020-10-22 08:54
Nailed it.  It was a Modular Routers bug, although a subtle one, only triggered by some other mod (not sure which) causing the GUI init() method to be called multiple times.  Next release (will upload today) will fix that.

**Comment by desht** [comment] 2020-10-22 09:01
Fixed in 7.1.1 release.

**Closed as completed by desht** 2020-10-22 09:01 UTC
Labels: bug, fixed in dev
