### ISSUE TITLE
Furnace product removal needs manual restart after initial run

### ISSUE THREAD

**Issue by TheWerdOfRa** [desht/ModularRouters#28] opened 2017-11-16 11:38 UTC
1.12.2 Minecraft Version
8.0.99.99 Forge Version
1.12.1-3.0.3 Mod Version
Used via the Horizons 3 FTB pack

I created a simple furnace setup with three routers, one to pull ores, one to pull coal, and one to push finished products using the Push/Pull MK2 modules. They all pull/push from the same chest and furnace as shown in picture.
![2017-11-16_11 25 22](https://user-images.githubusercontent.com/17488364/32889350-7e853c94-cac2-11e7-9255-6749d209bd3d.png)

Everything works for the first run, but soon the finished products router stops functioning. It happens when there is no more product to pull. For whatever reason it does not restart once new furnace outputs are present. Simply pulling any modules out and back in (of the impacted router) will restart the correct functions of the router, until it runs out of finished product again.

I tried playing with redstone clocks to try and reset it with a pulse (still not an ideal solution), but this had no impact. I also toggled eco mode and still no impact. I do not know of other work arounds, I would be happy to try your suggestions as I still have this setup created.

**Comment by desht** [comment] 2017-11-16 12:17
I just tried to reproduce this, and I can't.  The 3rd router is always able to pull from the furnace, even if the furnace's output slot has been empty for a while.

Could you post some more screenshots of that 3rd router perhaps?
* The open router GUI
* The puller module GUI in that router
* The sender module GUI in that router

**Comment by TheWerdOfRa** [comment] 2017-11-16 12:20
Sure!

GUI:
![2017-11-16_12 18 07](https://user-images.githubusercontent.com/17488364/32890830-4b588f96-cac8-11e7-95e6-ac111180350a.png)
![2017-11-16_12 18 12](https://user-images.githubusercontent.com/17488364/32890845-5898722a-cac8-11e7-838a-a8915d44e395.png)
![2017-11-16_12 18 16](https://user-images.githubusercontent.com/17488364/32890846-5a418a1c-cac8-11e7-961f-d290d65697e4.png)

The GUI's are not very helpful. I just bound them to the blocks and stuck them in. So the Puller is bound to the bottom of the Furnace, the pusher is bound to the clasp side of the chest.

**Comment by desht** [comment] 2017-11-16 12:29
Yeah, pretty much the default settings.  This is very strange.  Does the router just stop pulling, or does it pull and then not send the items on?

I'm guessing the puller module is getting itself confused somehow, but this is going to be hard to track down unless I can find a way to reproduce it...

**Comment by TheWerdOfRa** [comment] 2017-11-16 12:37
Yeah, I understand. The unit does not pull from the furnace, but does push it's last item to the chest. If I place items directly into the router, it restarts (much like replacing the modules does) so I am not sure how to test the pushing element alone.

I am using the FTB Horizons 3 mod-pack. I know they have server optimization items installed. I wonder if maybe there is something they changed that is interfering with this process. Obviously that would be on them, but I am not sure who/where to go to have them track this down.

**Comment by desht** [comment] 2017-11-16 12:47
Try blacklisting coal (or whatever fuel item you're using in your furnace).  Just a educated guess at this point, but I have a feeling it may resolve your problem.

**Comment by TheWerdOfRa** [comment] 2017-11-16 13:39
Success, thank you!

**Comment by desht** [comment] 2017-11-16 14:04
I guessed right :)

The problem (if you're interested) is that the furnace actually exposes a 2-slot inventory on the bottom face: slot 0 is the output, and slot 1 is the coal (which can't be pulled from).

The puller module finished extracting the furnace output and then moved onto the coal slot, tried to extract that... and failed.  Unfortunately, due to a badly-coded optimisation in my code, it then got stuck on that slot forever, even when an output item turned up again in slot 0.

That'll be properly fixed in the next release, but for now blacklisting the fuel item will work around the problem.

**Comment by desht** [comment] 2017-12-09 12:44
Implemented in new 3.1.0 release.

**Closed as completed by desht** 2017-12-09 12:44 UTC
