### ISSUE TITLE
Fluid duplication bug

### ISSUE THREAD

**Issue by MuteTiefling** [desht/ModularRouters#81] opened 2020-06-22 02:16 UTC
### Minecraft Version
1.15.2
### Forge Version
31.2.20
### Mod Version
PneumaticCraft 1.3.0-34
modular-routers-1.15.2-6.1.0-17
### Describe your problem, including steps to reproduce it

Bit of a cross mod interaction here, but Modular Routers is allowing me to duplicate fluids by way of the new PNC tanks. 

Place a tank and link a Fluid Module to it. 
Put a single bucket of any fluid in the tank.
Drop a full stack (or any quantity) of tanks inside the buffer of the router along with the card. 

That single bucket will be injected into all of the tanks in the stack, allowing you to dupe any quantity of fluids to 64x the amount. 

### Any other comments?

https://streamable.com/am8l35

**Comment by desht** [comment] 2020-06-22 10:22
Fixed in 6.1.1 release

**Comment by Iris-xii** [comment] 2022-01-25 02:17
This seems to be happening again in 1.16.4, reported here ( https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4132 ) but it's happening in a test instance as well.
![image](https://user-images.githubusercontent.com/48930896/150898243-7da1b820-e744-400a-83cc-d24934d35581.png)

Mods present in my test instance:
Forge 36.2.23
Patchouli-1.16.4-53.2
pneumaticcraft-repressurized-1.16.5-2.15.1-297
modular-routers-1.16.5-7.5.2-83

**Comment by desht** [comment] 2022-01-25 09:15
Confirmed.

**Comment by desht** [comment] 2022-01-25 09:24
Fixed in 7.5.3 release

**Closed as completed by desht** 2022-01-25 09:24 UTC
Labels: bug
