### ISSUE TITLE
Support for Refined Storage Crafters

### ISSUE THREAD

**Issue by ghost** [desht/ModularRouters#143] opened 2021-08-22 18:42 UTC
### Minecraft Version
1.16.5

### Forge Version
36.2.1
### Mod Version
This version of Modular Routers reports its version in the Mod's information as
"Version: task ':jar' property 'archiveVersion'"

### Describe your problem, including steps to reproduce it
I'm playing Enigmatica6-0.5.9 and I'm trying to use a modular router to accept recipe ingredients from a Refined Storage crafter, and route them to the right machines. Currently, Refined Storage keeps reporting 'machine doesn't accept item' when trying to insert into the router. I don't know if this is an API incompatibility or the fact that the recipe has multiple ingredients and the router has only a single slot for input. Perhaps there could be the addition of a 9-slot input stack, so that crafters could dump their ingredients, and the router could deal with then serially?

**Comment by desht** [comment] 2021-08-23 06:25
Won't be adding this, sorry. Modular Routers have a single buffer slot, by design.

You could insert into some kind of buffer block which then pushes items one at a time into the router. A vanilla hopper might work, although there are faster modded solutions of course.

**Closed as completed by desht** 2021-08-23 06:25 UTC
