### ISSUE TITLE
Harvest Crops?

### ISSUE THREAD

**Issue by RobertLSnead** [desht/ModularRouters#7] opened 2017-01-06 01:11 UTC
MC 1.10.2
modular-routers-1.10.2-1.2.1.jar

The placer is working fine for the crops if it is right in front of the router.  Range module does not work with crops.  Also the extruder module is not working to harvest the crops.  Also it would be nice if it supported friendly crops (aka right click to harvest).  Extruder module does not retrieve blocks.   Extruder limited to 24 blocks with maximum range of 64.

**Comment by desht** [comment] 2017-01-06 08:21
I can't reproduce any of the problems you mentioned:

- Range upgrades work fine with extruder modules (it doesn't work with placers, but never has, and isn't supposed to; placers place a single block and that is all)
- Extruder module has no problems harvesting vanilla or Actually Additions crops.  What crops are you testing with?
- Extruder module won't retrieve both the seeds and wheat (e.g. for wheat crops), since the router has only 1 slot in its buffer (which should be for holding the seeds).  This is not a bug.  If you need crops retrieved, a second router with a vacuum module could be used.  See demo video here where I do this: https://youtu.be/mb8ROLLLii4
- Maximum range of the extruder is 24 blocks by default (12 without range upgrades).  You can change that in config/modularrouters.cfg if you want to.

**Comment by desht** [comment] 2017-01-06 08:25
Also, I'm not really inclined to support "friendly" crops (which would basically mean auto-replanting).  Planting crops at range is already quite a powerful operation for something that needs no energy or tools (unlike farming devices like the EnderIO or Progressive Automation farmers).  The router isn't primarily a farming device, and I want to keep some balance there.

**Comment by RobertLSnead** [comment] 2017-01-08 15:21
Well... I figured out why it did not work and you do have some bugs for sure!  Changing the redstone mode did not work and caused strange behaviors, leaving as always on works just fine.  Also when using with crops if you alter, break, or manually place down when a redstone signal is on high, the router skips over that block as if it does not know what to do.  To fix you have to break the router and re-setup.  Other than that everything works fine.

**Comment by desht** [comment] 2017-01-08 18:29
1) Don''t change the Redstone mode then? :)  The Always or High modes is probably what you need here anyway (Low should reverse the signal meaning and Pulsed doesn't do anything useful at all for the Extruder module) 

2) The Extruder is likely to get confused if blocks are placed/removed manually; not sure I'd call that a bug, though. You just need to ensure that the crops don't get messed with (enclose the farm etc.) I'll take a look to see if the overall robustness can be improved in any way, no promises though. 

As I mentioned before, this is a cheap & easy way to auto farm, so the penalty for that is low efficiency and a certain level of extra manual care required.

**Comment by desht** [comment] 2017-01-09 12:29
So I've made one change in dev (soon to be uploaded as v1.2.2): if the extruder comes across an empty (or liquid) block while retracting, it will no longer stop in confusion, but simply skip over the empty block and continue to break blocks on the way back to the router.  This will get around the problem of broken crops causing the module to stop working.

As for manually placing down blocks in the extruder's way: don't do that :)  The extruder will stop extending if there's a block in the way, and that's not a bug.

**Comment by RobertLSnead** [comment] 2017-01-09 20:48
Beautiful update!  The extruder does not get confused.  I tested it and tried to mess it up, works perfectly!
Good job on the fix.  I'd say bug fixed :D

**Comment by desht** [comment] 2017-01-09 20:50
Good stuff!  Closing this issue now.

**Closed by desht** 2017-01-09 20:50 UTC
