### ISSUE TITLE
Terminate on process fail

### ISSUE THREAD

**Issue by Rodg88** [desht/ModularRouters#119] opened 2021-02-20 10:50 UTC
I'd like an option to terminate execution on fail, instead of just match.

I'm trying to make a single router mine a specific block above it, and if it does mine it, delete it, pick up a block form an inv below and place the new block in the world above. As it currently is, there's no way to terminate with an empty buffer (as far as I can tell), so each time it runs it picks up the block from the inv below, and I need to add a module to put it back. What I'd like is it to be able to terminate on a detector module fail. So I'd have a filtered block breaker module, then the detector module, void module, then pull/place.

So if the block above is broken, it can match the mined block with the detector and continue, otherwise terminate when the detector fails.

**Comment by desht** [comment] 2021-02-20 11:40
Duplicate of #117 

That's actually already done in-dev, and will be in the next release.

**Closed as completed by desht** 2021-02-20 11:40 UTC
Labels: duplicate
