### ISSUE TITLE
Dupe on Modular router

### ISSUE THREAD

**Issue by syrun97** [desht/ModularRouters#39] opened 2018-05-27 05:32 UTC
### Minecraft Version
1.12.2
### Forge Version
14.23.3.2679
### Mod Version
1.12.2-3.1.4
### Describe your problem, including steps to reproduce it
https://www.youtube.com/watch?v=bjFY7eGHyH4&feature=youtu.be
Dupe Items when flinger/dropper module and vacuum module is installed in one router.
### Any other comments?
it happend on sevtech age modpack.

**Comment by desht** [comment] 2018-05-27 10:46
Thanks, I'll take a look ASAP but I'm away from any computers for the next couple of days..

**Comment by desht** [comment] 2018-05-30 16:50
I can't reproduce this at all.  The number of items in the router remains static, as I would expect.  This is in my test instance, so it's possible some other mod in Sevtech is interfering.  I'll try to test in Sevtech and see what happens there.

**Comment by desht** [comment] 2018-05-30 17:20
OK, it happens in Sevtech but not in any of my test worlds.  The Dropper/Flinger create the items entities in Sevtech, but the item doesn't get removed from the router's buffer.

I suspect whichever mod causes item entities to render flat on the ground is also somehow causing ``World#spawnEntity()`` to return ``false`` (probably intercepting the ``EntityJoinWorldEvent``, which would stop the code from extracting the item from the buffer.

Looking at the ``spawnEntity()`` code, I can probably safely ignore the return value, and always extract the item from the buffer, which would resolve this problem.

**Comment by desht** [comment] 2018-05-31 11:05
Fixed in 3.1.5 release.

**Closed as completed by desht** 2018-05-31 11:05 UTC
Labels: mod incompatibility
